import type { Metadata } from 'next';
import localFont from 'next/font/local';

import '@/global/styles/globals.css';

const Fixel = localFont({
  src: [
    {
      path: '../public/fonts/Fixel/FixelText-Thin.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/Fixel/FixelText-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Fixel/FixelText-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/Fixel/FixelText-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
});

export const metadata: Metadata = {
  title: 'Lystivnyk',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={Fixel.className}>{children}</body>
    </html>
  );
}
